messages:
  add: '&eLectern added to interdiction list'
  add-failed: '&cThat lectern is already interdicted'
  del: '&eLectern removed from interdiction list'
  del-failed: '&cLectern is not on the interdiction list'
  hands-off: '&cYou cannot take this book'
  player-only: 'This command is for players in-game only'
  access-denied: '&cAccess denied!'
  already-marking: '&cYou are already in marking mode'
  marking: '&eRight click the lectern, any other block to cancel'
  marking-aborted: '&eMarking aborted'
  help-add: '&e/homb add &7- &6Allows you to add a lectern to be interdicted'
  help-del: '&e/homb del &7- &6Removes restriction from a lectern'
  help-list: '&e/homb list &7- &6Lists interdicted lecterns'
  list-none: '&cThere are no interdicted lecterns'
  list-header: '&eInterdicted lectern locations:%br%'
  list-data: '&6%location%'
