name: HandsOffMyBook
author: Strahan
main: com.sylvcraft.HandsOffMyBook
version: 1.1
api-version: 1.14
description: Stops people from taking books off of specific lecterns
commands:
  homb:
    description: Plugin command
